#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on bionic-queens."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='bionic')
    deployment.run_tests()
