#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on cosmic-rocky."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='cosmic')
    deployment.run_tests()
