#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on xenial-pike."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='xenial',
                                        openstack='cloud:xenial-pike',
                                        source='cloud:xenial-updates/pike')
    deployment.run_tests()
