#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on bionic-rocky."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='bionic',
                                        openstack='cloud:bionic-rocky',
                                        source='cloud:bionic-updates/rocky')
    deployment.run_tests()
