#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on zesty-ocata."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='zesty')
    deployment.run_tests()
