#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on xenial-ocata."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='xenial',
                                        openstack='cloud:xenial-ocata',
                                        source='cloud:xenial-updates/ocata')
    deployment.run_tests()
