#!/usr/bin/env python

"""Amulet tests on a basic quantum-gateway deployment on xenial-queens."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='xenial',
                                        openstack='cloud:xenial-queens',
                                        source='cloud:xenial-updates/queens')
    deployment.run_tests()
